# Sample config for Prometheus.
- targets:
    - 192.168.0.230:9100
  labels:
    os: 'linux'
    family: 'Centos'
    role: 'servers'
    services: Docker
    env: Test

- targets:
    - 192.168.0.215:9100
  labels:
    os: 'linux'
    family: 'Ubuntu'
    role: 'servers'
    services: Docker
    env: Prod
